### ISSUE TITLE
Add optional validator

### ISSUE THREAD

**Issue by eugene-p** [sailorproject/valua#10]
Would be cool to have ability to mark value as optional.

I see 3 options
### Have a second parameter for validation e.g:

``` lua
value = nil -- or value = ""
valua:new().type("string").len(3,5)(value) -- returns false
valua:new().type("string").len(3,5)(value, true) -- returns true
```
### Have a parameter on creation e.g:

``` lua
value = nil -- or value = ""
valua:new().type("string").len(3,5)(value) -- returns false
valua:new(true).type("string").len(3,5)(value) -- returns true
```
### Have stackable function e.g:

``` lua
value = nil -- or value = ""
valua:new().type("string").len(3,5)(value) -- returns false
valua:new().optional().type("string").len(3,5)(value) -- returns true
```

**Comment by Etiene** [comment]
You mean it is only validated if it's different than nil or empty string? Yea :) We could arrange that :)

**Comment by eugene-p** [comment]
Exactly. Not sure though if 0 should act the same

**Comment by Etiene** [comment]
0 definitely shouldn't act the same way! I think it would go against with some very basic Lua principles. Normally I wouldn't even be sure about  empty strings either but the thing is thay I use valua mainly for sailor which means form web input so it's never nil and rather an empty string. What do you think about that?

**Comment by eugene-p** [comment]
Same here. That is why I mentioned empty string.

**Comment by eugene-p** [comment]
So have some time this week and can take a crack at this issue. What would be the better way to implement optional parameter? 

I also found commit https://github.com/sailorproject/valua/commit/e9993772d4002cba55e9865d695c7a6bfebd95eb

Would it make more sense to revert those to original way and handle empty through optional flag/parameter/function  though i do anderstand that it would brake compatibility.

**Comment by d9k** [comment]
It must be `optional()` method for validator declaration. For example database table may have default values for some fields of any type.
It's sad that this feature isn't implemented yet :c

**Comment by d9k** [comment]
@Etiene, please review mine pull request:
https://github.com/sailorproject/valua/pull/19
