### ISSUE TITLE
Error installing valua with luarocks install command

### ISSUE THREAD

**Issue by xspager** [sailorproject/valua#9]
If you try to install valua with luarock's install command you get the error:

`cp: cannot stat ‘valua.lua’: No such file or directory`

Changing the rockspeck on https://github.com/sailorproject/valua/blob/master/rockspecs/valua-0.3-1.rockspec#L22 to

`valua = "valua/valua.lua"`

allows me to install using luarock's make command

**Comment by ignacio** [comment]
Had no problem at all when installing using LuaRocks 2.3.0 and Lua 5.1.

```
C:\Users\ignacio>luarocks install valua
Installing https://luarocks.org/valua-0.3-1.src.rock...
Using https://luarocks.org/valua-0.3-1.src.rock... switching to 'build' mode
Updating manifest for d:\dropbox\lua\5.1\/lib/luarocks/rocks
valua 0.3-1 is now built and installed in d:\dropbox\lua\5.1\ (license: MIT)
```

Can you provide more information? Try `luarocks install valua --verbose`

**Comment by ignacio** [comment]
Any news on this?

**Comment by Etiene** [comment]
I think he was using an older version of LuaRocks and it got solved when
updating. If I remember it well, he mentioned this on another issue at
Sailor. Waiting confirmation to close this.

2016-03-01 21:25 GMT+01:00 Ignacio Burgueño <notifications@github.com>:

> Any news on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sailorproject/valua/issues/9#issuecomment-190886416>.
>



-- 
Etiene Dalcol

Software Engineering student at ENSTA Bretagne and PUC-Rio
Sailor Developer http://sailorproject.org
Lua Ladies Founder http://lualadies.org

**Comment by xspager** [comment]
Oh, sorry, yeah, probably an distro provided luarocks :/

**Comment by Etiene** [comment]
:+1:
